package com.oorja.rewardsystem.entity;

import jakarta.persistence.*;


/**
 * Entity representing an answer submitted by a customer for a quiz question.
 *
 * This class is mapped to a database table using JPA. Each Answer record
 * stores the response submitted by a customer, whether it was correct,
 * and the associated customer and question.
 */
@Entity
public class Answer {

    /**
     * Unique identifier for the answer.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The answer text submitted by the customer.
     */
    private String submittedAnswer;

    /**
     * Indicates whether the submitted answer is correct.
     */
    private boolean correct;

    /**
     * The customer who submitted this answer.
     * Multiple answers can be associated with a single customer.
     */
    @ManyToOne
    private Customer customer;

    /**
     * The question that this answer corresponds to.
     * Multiple answers can be associated with the same question.
     */
    @ManyToOne
    private Question question;

    /**
     * Default constructor required by JPA.
     */
    public Answer() {}

    /**
     * Constructs an Answer object with the provided details.
     *
     * @param submittedAnswer the answer provided by the customer
     * @param correct whether the submitted answer is correct
     * @param customer the customer who submitted the answer
     * @param question the question being answered
     */
    public Answer(String submittedAnswer, boolean correct,
        Customer customer, Question question) {
        this.submittedAnswer = submittedAnswer;
        this.correct = correct;
        this.customer = customer;
        this.question = question;
    }
}