package com.oorja.rewardsystem.entity;

import jakarta.persistence.*;

/**
 * Entity representing a customer in the reward system.
 *
 * Each customer can participate in quizzes and earn reward points
 * based on the correctness of their answers.
 */
@Entity
public class Customer {

    /**
     * This is unique identifier for the customer.
     * This value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The number of reward points accumulated by the customer.
     * The default value is initialized to 0.
     */
    private int rewardPoints = 0;

    /**
     * Version field used for optimistic locking.
     * This helps prevent concurrent update conflicts when multiple
     * transactions attempt to modify the same customer record.
     */
    @Version
    private Long version;

    /**
     * Default constructor required by JPA.
     */
    public Customer() {}


    /**
     * Returns the unique ID of the customer.
     *
     * @return the customer ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the current reward points of the customer.
     *
     * @return the reward points
     */
    public int getRewardPoints() {
        return rewardPoints;
    }

    /**
     * Updates the reward points of the customer.
     *
     * @param rewardPoints the new reward points value
     */
    public void setRewardPoints(int rewardPoints) {
        this.rewardPoints = rewardPoints;
    }
}