package com.oorja.rewardsystem.entity;

import jakarta.persistence.*;

/**
 * Entity representing a quiz question in the reward system.
 *
 * Each Question contains the text of the question and the
 * correct answer that will be used to evaluate customer responses.
 */
@Entity
public class Question {

    /**
     * Unique identifier for the question.
     * The value is automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * The text content of the question presented to customers.
     */
    private String questionText;


    /**
     * The correct answer to the question.
     * This value is used to determine whether a submitted answer is correct.
     */
    private String correctAnswer;

    /**
     * Default constructor required by JPA.
     */
    public Question() {}

    /**
     * Constructs a Question with the specified text and correct answer.
     *
     * @param questionText the text of the question
     * @param correctAnswer the correct answer for the question
     */
    public Question(String questionText, String correctAnswer) {
        this.questionText = questionText;
        this.correctAnswer = correctAnswer;
    }

    /**
     * Returns the unique ID of the question.
     *
     * @return the question ID
     */
    public Long getId() {
        return id;
    }

    /**
     * Returns the text of the question.
     *
     * @return the question text
     */
    public String getQuestionText() {
        return questionText;
    }

    /**
     * Returns the correct answer for the question.
     *
     * @return the correct answer
     */
    public String getCorrectAnswer() {
        return correctAnswer;
    }

    /**
     * Updates the text of the question.
     *
     * @param questionText the new question text
     */
    public void setQuestionText(String questionText) {
        this.questionText = questionText;
    }

    /**
     * Updates the correct answer for the question.
     *
     * @param correctAnswer the new correct answer
     */
    public void setCorrectAnswer(String correctAnswer) {
        this.correctAnswer = correctAnswer;
    }

}